
[[services]]
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[services]]
  internal_port = 4242
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    # This opens raw TCP port 4242 to the public internet for PuTTY
    port = 4242
